# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""
vLLM backend configuration.

Implements BackendProtocol for vLLM inference serving with prefill/decode disaggregation.
Uses dynamo.vllm integration module.
"""

from __future__ import annotations

import builtins
import json
from collections.abc import Sequence
from dataclasses import field
from pathlib import Path
from typing import (
    TYPE_CHECKING,
    Any,
    ClassVar,
    Literal,
)

from marshmallow import Schema
from marshmallow_dataclass import dataclass

from srtctl.ports import (
    DYN_SYSTEM_PORT_BASE,
    MOONCAKE_HTTP_METADATA_PORT,
    MOONCAKE_MASTER_PORT,
    VLLM_DATA_PARALLEL_RPC_PORT,
    VLLM_PORT_BASE,
    VLLM_PORT_STRIDE,
)

if TYPE_CHECKING:
    from srtctl.backends.base import SrunConfig
    from srtctl.core.runtime import RuntimeContext
    from srtctl.core.schema import ProfilingConfig
    from srtctl.core.topology import Endpoint, NodePortAllocator, Process

# Type alias for worker modes
WorkerMode = Literal["prefill", "decode", "agg"]
DPLaunchMode = Literal["per_gpu", "per_node"]

# Filename for the mooncake-store JSON config srtslurm writes to log_dir at job
# start. log_dir is mounted into every worker at /logs, so workers read the JSON
# from MOONCAKE_STORE_CONFIG_CONTAINER_PATH.
MOONCAKE_STORE_CONFIG_FILENAME = "mooncake_store_config.json"
MOONCAKE_STORE_CONFIG_CONTAINER_PATH = f"/logs/{MOONCAKE_STORE_CONFIG_FILENAME}"


@dataclass(frozen=True)
class VLLMMooncakeKVStoreConfig:
    """Mooncake KV store config for the vLLM backend.

    When present, srtslurm launches ``mooncake_master`` on the infra node
    (co-located with etcd/nats) using the shared SGLang launch command and
    injects on every vLLM worker::

        MOONCAKE_MASTER              = <infra_ip>:8700
        MOONCAKE_TE_META_DATA_SERVER = http://<infra_ip>:8701/metadata
        MOONCAKE_LOCAL_HOSTNAME      = <worker_ip>
        MOONCAKE_CONFIG_PATH         = /logs/mooncake_store_config.json

    The JSON file referenced by ``MOONCAKE_CONFIG_PATH`` is generated by
    srtslurm at job start (see ``do_sweep.start_mooncake_master``) from
    ``store_config`` below. vLLM's ``MooncakeStoreConnector`` reads this
    file via ``MooncakeStoreConfig.load_from_env()``.

    ``env:`` is injected on every vLLM worker (alongside the auto-stamped
    ``MOONCAKE_*`` vars above), not on the standalone ``mooncake_master``
    daemon — the master srun command passes no env. Use this for
    in-process Mooncake C++ libraries linked into the worker:
    ``MC_*`` knobs read by the transfer engine / store client
    (e.g. ``MC_ENABLE_DEST_DEVICE_AFFINITY``, ``MC_STORE_CLIENT_METRIC``,
    ``MC_TE_METRIC``), and any ``MOONCAKE_*`` overrides the connector
    consults.

    Example YAML::

        backend:
          type: vllm
          mooncake_kv_store:
            container: inferactinc/public:mk-int-20260507  # optional
            env:                              # injected on every worker
              MC_ENABLE_DEST_DEVICE_AFFINITY: "1"   # in-process Mooncake C++ knobs
              MC_STORE_CLIENT_METRIC: "1"
            store_config:                     # MooncakeStoreConfig JSON keys
              metadata_server: "P2PHANDSHAKE"
              global_segment_size: "100GB"
              local_buffer_size: "4GB"
              protocol: "rdma"
              device_name: ""
              # master_server_address: srtslurm auto-fills from infra IP
    """

    container: str | None = None
    env: dict[str, str] = field(default_factory=dict)
    # ``store_config`` values are JSON-serialized into MOONCAKE_CONFIG_PATH and
    # parsed by vLLM's ``MooncakeStoreConfig`` dataclass — fields are a mix of
    # str (e.g. ``protocol``), int (e.g. ``port``), and human-readable sizes
    # (e.g. ``"4GB"``). Type as ``dict[str, Any]`` to avoid forcing users to
    # quote numeric values.
    store_config: dict[str, Any] | None = None

    Schema: ClassVar[builtins.type[Schema]] = Schema


@dataclass(frozen=True)
class VLLMServerConfig:
    """vLLM server CLI configuration per mode (prefill/decode/aggregated).

    Each mode can have its own configuration dict that gets converted
    to CLI flags when starting the worker. These are passed directly to
    vLLM's AsyncEngineArgs.
    """

    prefill: dict[str, Any] | None = None
    decode: dict[str, Any] | None = None
    aggregated: dict[str, Any] | None = None

    Schema: ClassVar[type[Schema]] = Schema


@dataclass(frozen=True)
class VLLMProtocol:
    """vLLM protocol - implements BackendProtocol.

    This frozen dataclass both holds configuration AND implements the
    BackendProtocol methods for process allocation and launching.

    dynamo 1.0.0+: ``--connector`` was removed; the ``connector`` field is now
    translated to ``--kv-transfer-config`` with the appropriate JSON payload.

    Example YAML:
        backend:
          type: vllm
          connector: nixl  # translated to --kv-transfer-config JSON
          allow_prefill_decode_colocation: true  # pack P/D on one node when all workers fit
          allow_prefill_decode_colocation_across_nodes: true  # continue packing on later nodes
          dp_launch_mode: per_node  # one process manages all local DP ranks
          decode_dp_launch_mode: per_gpu  # optional per-role override
          prefill_environment:
            PYTHONUNBUFFERED: "1"
          vllm_config:
            prefill:
              tensor-parallel-size: 2
              gpu-memory-utilization: 0.9
              connector: lmcache  # override connector for prefill
            decode:
              tensor-parallel-size: 2
              gpu-memory-utilization: 0.85
              # uses default connector (nixl)
    """

    type: Literal["vllm"] = "vllm"

    # Environment variables per mode
    prefill_environment: dict[str, str] = field(default_factory=dict)
    decode_environment: dict[str, str] = field(default_factory=dict)
    aggregated_environment: dict[str, str] = field(default_factory=dict)

    # vLLM server CLI config per mode
    vllm_config: VLLMServerConfig | None = None

    # Legacy device binding for vLLM builds without --device-ids.
    set_cuda_visible_devices: bool = False

    # Default KV connector: "nixl", "lmcache", or a raw JSON string for --kv-transfer-config.
    # Can be overridden per mode by setting "connector" in vllm_config.prefill/decode/aggregated.
    # dynamo 1.0.0+: translated to --kv-transfer-config (--connector was removed).
    connector: str | None = "nixl"

    # Mooncake KV store — when set, srtslurm launches mooncake_master on the
    # infra node and auto-injects MOONCAKE_MASTER / MOONCAKE_TE_META_DATA_SERVER
    # / MOONCAKE_LOCAL_HOSTNAME on every vLLM worker.
    mooncake_kv_store: VLLMMooncakeKVStoreConfig | None = None

    # KV events config - enables --kv-events-config with auto-allocated ports.
    # Required for Dynamo's event-driven KV-aware routing.
    # Global true enables defaults for prefill and decode workers.
    # Per-mode: {"prefill": true, "decode": {"topic": "custom"}}
    kv_events_config: bool | dict[str, Any] | None = None

    # Allow prefill and decode workers to share one node when the combined GPU
    # request fits within gpus_per_node. Defaults off to preserve existing P/D
    # node separation.
    allow_prefill_decode_colocation: bool = False

    # Extend P/D colocation to multi-node topologies. When enabled together
    # with allow_prefill_decode_colocation, workers are packed contiguously
    # across the minimum number of nodes instead of reserving separate P/D
    # node pools. Defaults off to preserve the original one-node-only policy.
    allow_prefill_decode_colocation_across_nodes: bool = False

    # DP process layout. Keep the existing per-GPU behavior by default;
    # per-node lets vLLM manage local DP ranks in one CUDA namespace.
    dp_launch_mode: DPLaunchMode = "per_gpu"

    # Optional per-role overrides. Unset roles inherit dp_launch_mode.
    prefill_dp_launch_mode: DPLaunchMode | None = None
    decode_dp_launch_mode: DPLaunchMode | None = None
    aggregated_dp_launch_mode: DPLaunchMode | None = None

    Schema: ClassVar[builtins.type[Schema]] = Schema

    # =========================================================================
    # BackendProtocol Implementation
    # =========================================================================

    def get_srun_config(self) -> SrunConfig:
        """vLLM launches one srun step for each generated process."""
        from srtctl.backends.base import SrunConfig

        return SrunConfig(mpi=None, oversubscribe=False, launch_per_endpoint=False)

    def get_config_for_mode(self, mode: WorkerMode) -> dict[str, Any]:
        """Get merged config dict for a worker mode."""
        if not self.vllm_config:
            return {}

        if mode == "prefill":
            return dict(self.vllm_config.prefill or {})
        elif mode == "decode":
            return dict(self.vllm_config.decode or {})
        elif mode == "agg":
            return dict(self.vllm_config.aggregated or {})
        return {}

    def get_kv_events_config_for_mode(self, mode: WorkerMode) -> dict[str, Any] | None:
        """Get --kv-events-config payload for a worker mode."""
        if not self.kv_events_config:
            return None

        if self.kv_events_config is True:
            if mode in ("prefill", "decode"):
                return {
                    "publisher": "zmq",
                    "topic": "kv-events",
                    "enable_kv_cache_events": True,
                }
            return None

        if isinstance(self.kv_events_config, dict):
            mode_cfg = self.kv_events_config.get("aggregated") if mode == "agg" else self.kv_events_config.get(mode)
            if mode_cfg is None:
                return None
            if mode_cfg is True:
                return {
                    "publisher": "zmq",
                    "topic": "kv-events",
                    "enable_kv_cache_events": True,
                }
            if isinstance(mode_cfg, dict):
                result = {
                    "publisher": "zmq",
                    "topic": "kv-events",
                    "enable_kv_cache_events": True,
                }
                result.update(mode_cfg)
                return result

        return None

    def get_environment_for_mode(self, mode: WorkerMode) -> dict[str, str]:
        """Get environment variables for a worker mode."""
        if mode == "prefill":
            return dict(self.prefill_environment)
        elif mode == "decode":
            return dict(self.decode_environment)
        elif mode == "agg":
            return dict(self.aggregated_environment)
        return {}

    def get_process_environment(self, process: Process) -> dict[str, str]:
        """Get process-specific environment variables for vLLM workers.

        vLLM with dynamo requires unique ports for each worker:
        - DYN_VLLM_KV_EVENT_PORT: ZMQ port for KV events publishing
        - VLLM_NIXL_SIDE_CHANNEL_PORT: Port for NIXL side channel transfers
        - VLLM_NIXL_SIDE_CHANNEL_HOST: Routable IP for NIXL side channel
          (vLLM defaults to ``0.0.0.0`` / ``localhost`` which breaks the
          multi-node NIXL handshake)
        - VLLM_PORT: private base for vLLM's get_open_port() scans, unique per
          process so co-located workers don't race for the same rendezvous port
          (see the notes on VLLM_PORT_BASE in srtctl.ports)
        """
        from srtctl.core.slurm import get_hostname_ip

        env: dict[str, str] = {}
        if process.kv_events_port is not None:
            env["DYN_VLLM_KV_EVENT_PORT"] = str(process.kv_events_port)
        if process.nixl_port is not None:
            env["VLLM_NIXL_SIDE_CHANNEL_PORT"] = str(process.nixl_port)
            env["VLLM_NIXL_SIDE_CHANNEL_HOST"] = get_hostname_ip(process.node)
        # Unique per-process VLLM_PORT base to avoid EADDRINUSE rendezvous races
        # when endpoints are co-located on a node. E.g. PD 4xDEP2+1xDEP8 on
        # 4xGB200 nodes: each prefill endpoint is DEP2 (uses 2 of the 4 GPUs), so
        # two endpoints share one physical node and would otherwise scan
        # overlapping get_open_port() ranges.
        proc_index = max(process.sys_port - DYN_SYSTEM_PORT_BASE, 0)
        env["VLLM_PORT"] = str(VLLM_PORT_BASE + proc_index * VLLM_PORT_STRIDE)
        return env

    def get_mooncake_worker_env(self, infra_node_ip: str, local_hostname: str) -> dict[str, str]:
        """Get mooncake env vars to inject on a specific vLLM worker.

        Returns ``{}`` when ``mooncake_kv_store`` is unset. Otherwise:

        - ``MOONCAKE_MASTER`` and ``MOONCAKE_TE_META_DATA_SERVER`` are always
          stamped by srtslurm (the user can't know the infra IP at config time).
        - ``MOONCAKE_LOCAL_HOSTNAME`` defaults to the worker's resolved IP for
          multi-node peer transfers, but a value in ``mooncake_kv_store.env``
          wins (use this to pin to a specific RDMA NIC IP).
        - ``MOONCAKE_CONFIG_PATH`` points to the JSON file srtslurm writes at
          job start (mounted into the container at ``/logs``). vLLM's
          ``MooncakeStoreConnector`` requires this — it does not read the
          ``MOONCAKE_*`` env vars directly.
        """
        if self.mooncake_kv_store is None:
            return {}
        return {
            "MOONCAKE_LOCAL_HOSTNAME": local_hostname,
            **self.mooncake_kv_store.env,
            "MOONCAKE_MASTER": f"{infra_node_ip}:{MOONCAKE_MASTER_PORT}",
            "MOONCAKE_TE_META_DATA_SERVER": (f"http://{infra_node_ip}:{MOONCAKE_HTTP_METADATA_PORT}/metadata"),
            "MOONCAKE_CONFIG_PATH": MOONCAKE_STORE_CONFIG_CONTAINER_PATH,
        }

    def build_mooncake_store_config(self, infra_node_ip: str) -> dict[str, Any]:
        """Build the JSON payload for vLLM's ``MooncakeStoreConfig.load_from_env()``.

        Pass-through of ``mooncake_kv_store.store_config`` with
        ``master_server_address`` force-overridden to the infra node IP
        (the user can't know that at config time). srtslurm intentionally
        does not provide defaults for the other fields — values like
        ``global_segment_size``, ``protocol``, and ``device_name`` are
        hardware-specific and silently using a default is worse than
        failing loudly. Set them explicitly in YAML; see
        ``docs/mooncake-kv-store.md``.
        """
        result: dict[str, Any] = {}
        if self.mooncake_kv_store is not None and self.mooncake_kv_store.store_config:
            result.update(self.mooncake_kv_store.store_config)
        result["master_server_address"] = f"{infra_node_ip}:{MOONCAKE_MASTER_PORT}"
        return result

    def get_served_model_name(self, default: str) -> str:
        """Get served model name from vLLM config, or return default."""
        if self.vllm_config:
            for cfg in [self.vllm_config.prefill, self.vllm_config.aggregated, self.vllm_config.decode]:
                if cfg:
                    name = cfg.get("served-model-name") or cfg.get("served_model_name")
                    if name:
                        return name
        return default

    def should_colocate_prefill_decode(
        self,
        *,
        num_prefill: int,
        num_decode: int,
        num_agg: int,
        gpus_per_prefill: int,
        gpus_per_decode: int,
        gpus_per_agg: int,
        gpus_per_node: int,
    ) -> bool:
        """Whether prefill and decode workers should be packed contiguously."""
        if not self.allow_prefill_decode_colocation:
            return False
        if num_prefill <= 0 or num_decode <= 0 or gpus_per_node <= 0:
            return False

        total_worker_gpus = num_prefill * gpus_per_prefill + num_decode * gpus_per_decode + num_agg * gpus_per_agg
        return total_worker_gpus <= gpus_per_node or self.allow_prefill_decode_colocation_across_nodes

    def allocate_endpoints(
        self,
        num_prefill: int,
        num_decode: int,
        num_agg: int,
        gpus_per_prefill: int,
        gpus_per_decode: int,
        gpus_per_agg: int,
        gpus_per_node: int,
        available_nodes: Sequence[str],
        spread_workers: bool = False,
    ) -> list[Endpoint]:
        """Allocate endpoints to nodes."""
        from srtctl.core.topology import allocate_endpoints

        return allocate_endpoints(
            num_prefill=num_prefill,
            num_decode=num_decode,
            num_agg=num_agg,
            gpus_per_prefill=gpus_per_prefill,
            gpus_per_decode=gpus_per_decode,
            gpus_per_agg=gpus_per_agg,
            gpus_per_node=gpus_per_node,
            available_nodes=available_nodes,
            spread_workers=spread_workers,
            allow_prefill_decode_colocation=self.should_colocate_prefill_decode(
                num_prefill=num_prefill,
                num_decode=num_decode,
                num_agg=num_agg,
                gpus_per_prefill=gpus_per_prefill,
                gpus_per_decode=gpus_per_decode,
                gpus_per_agg=gpus_per_agg,
                gpus_per_node=gpus_per_node,
            ),
        )

    def _is_dp_mode(self, mode: WorkerMode) -> bool:
        """Check if this mode uses Data Parallel + Expert Parallel pattern.

        DP+EP mode is detected when data-parallel-size is set in the mode's config.
        ``dp_launch_mode`` controls whether a process owns one rank or all local ranks.
        """
        config = self.get_config_for_mode(mode)
        return config.get("data-parallel-size") is not None or config.get("data_parallel_size") is not None

    def _get_dp_size(self, mode: WorkerMode) -> int | None:
        """Get the data-parallel-size for a mode, or None if not in DP mode."""
        config = self.get_config_for_mode(mode)
        return config.get("data-parallel-size") or config.get("data_parallel_size")

    def get_dp_launch_mode_for_mode(self, mode: WorkerMode) -> DPLaunchMode:
        """Return the role-specific launch mode or the global default."""
        overrides = {
            "prefill": self.prefill_dp_launch_mode,
            "decode": self.decode_dp_launch_mode,
            "agg": self.aggregated_dp_launch_mode,
        }
        return overrides[mode] or self.dp_launch_mode

    def get_expected_dynamo_worker_counts(self, processes: Sequence[Process]) -> tuple[int, int]:
        """Return the generate-instance counts expected from a process layout.

        Per-GPU processes each register one instance. Hybrid per-node processes
        register their local rank range, while non-hybrid headless followers do
        not register separately.
        """
        grouped: dict[tuple[WorkerMode, int], list[Process]] = {}
        for process in processes:
            key = (process.endpoint_mode, process.endpoint_index)
            grouped.setdefault(key, []).append(process)

        prefill_count = 0
        decode_count = 0
        for (mode, _endpoint_index), endpoint_processes in grouped.items():
            registrations = 1
            if self._is_dp_mode(mode):
                launch_mode = self.get_dp_launch_mode_for_mode(mode)
                if launch_mode == "per_gpu":
                    registrations = len(endpoint_processes)
                else:
                    config = self.get_config_for_mode(mode)
                    hybrid_lb = config.get("data-parallel-hybrid-lb", config.get("data_parallel_hybrid_lb", False))
                    hybrid_lb_enabled = hybrid_lb is True or (
                        isinstance(hybrid_lb, str) and hybrid_lb.strip().lower() in {"1", "true", "yes", "on"}
                    )
                    registrations = len(endpoint_processes) if hybrid_lb_enabled else 1

            if mode == "prefill":
                prefill_count += registrations
            else:
                decode_count += registrations

        return prefill_count, decode_count

    def should_set_cuda_visible_devices(self, process: Process) -> bool:
        """Whether worker_stage should set CUDA_VISIBLE_DEVICES.

        Newer vLLM builds should use ``--device-ids`` instead. Older builds
        before https://github.com/vllm-project/vllm/pull/45026 should set
        CUDA_VISIBLE_DEVICES.
        """
        return self.set_cuda_visible_devices

    def endpoints_to_processes(
        self,
        endpoints: list[Endpoint],
        base_sys_port: int = DYN_SYSTEM_PORT_BASE,
        port_allocator: NodePortAllocator | None = None,
    ) -> list[Process]:
        """Convert endpoints to processes.

        DP+EP mode uses the configured per-GPU or per-node process layout.
        For standard TP mode, creates one process per node.
        """
        from srtctl.core.topology import NodePortAllocator, endpoints_to_processes

        dp_endpoints = [endpoint for endpoint in endpoints if self._is_dp_mode(endpoint.mode)]
        if not dp_endpoints:
            # Standard TP mode: one process per node
            return endpoints_to_processes(endpoints, base_sys_port=base_sys_port, port_allocator=port_allocator)

        launch_modes = {self.get_dp_launch_mode_for_mode(endpoint.mode) for endpoint in dp_endpoints}
        if launch_modes == {"per_node"}:
            return self._dp_per_node_endpoints_to_processes(
                endpoints,
                base_sys_port=base_sys_port,
                port_allocator=port_allocator,
            )

        if launch_modes == {"per_gpu"}:
            return self._dp_per_gpu_endpoints_to_processes(
                endpoints,
                base_sys_port=base_sys_port,
                port_allocator=port_allocator,
            )

        # Mixed role modes share one allocator so every coordination port stays
        # unique across the per-node and per-GPU process groups.
        processes: list[Process] = []
        current_sys_port = base_sys_port
        if port_allocator is None:
            port_allocator = NodePortAllocator()

        for endpoint in endpoints:
            if self._is_dp_mode(endpoint.mode) and self.get_dp_launch_mode_for_mode(endpoint.mode) == "per_node":
                endpoint_processes = self._dp_per_node_endpoints_to_processes(
                    [endpoint],
                    base_sys_port=current_sys_port,
                    port_allocator=port_allocator,
                )
            else:
                endpoint_processes = self._dp_per_gpu_endpoints_to_processes(
                    [endpoint],
                    base_sys_port=current_sys_port,
                    port_allocator=port_allocator,
                )
            processes.extend(endpoint_processes)
            current_sys_port += len(endpoint_processes)

        return processes

    def _dp_per_gpu_endpoints_to_processes(
        self,
        endpoints: list[Endpoint],
        base_sys_port: int = DYN_SYSTEM_PORT_BASE,
        port_allocator: NodePortAllocator | None = None,
    ) -> list[Process]:
        """Convert DP endpoints to one process per GPU."""
        from srtctl.core.topology import NodePortAllocator, Process

        # DP+EP mode: one process per GPU
        processes: list[Process] = []
        current_sys_port = base_sys_port
        if port_allocator is None:
            port_allocator = NodePortAllocator()

        for endpoint in endpoints:
            if not self._is_dp_mode(endpoint.mode):
                # Non-DP endpoints get standard processing
                # (This shouldn't happen in practice since all modes should be consistent)
                for node_rank, node in enumerate(endpoint.nodes):
                    is_leader = node_rank == 0
                    http_port = port_allocator.next_http_port(node) if is_leader else 0
                    bootstrap_port = (
                        port_allocator.next_bootstrap_port(node) if endpoint.mode == "prefill" and is_leader else None
                    )
                    kv_events_port = port_allocator.next_kv_events_port()
                    nixl_port = port_allocator.next_nixl_port()

                    processes.append(
                        Process(
                            node=node,
                            gpu_indices=endpoint.gpu_indices,
                            sys_port=current_sys_port,
                            http_port=http_port,
                            endpoint_mode=endpoint.mode,
                            endpoint_index=endpoint.index,
                            node_rank=node_rank,
                            bootstrap_port=bootstrap_port,
                            kv_events_port=kv_events_port,
                            nixl_port=nixl_port,
                        )
                    )
                    current_sys_port += 1
            else:
                # DP+EP mode: one process per GPU
                # Each process gets a single GPU and a unique dp_rank
                dp_rank = 0
                # Allocate a unique DP RPC port for this endpoint's leader node
                dp_rpc_port = port_allocator.next_dp_rpc_port(endpoint.leader_node)
                # Allocate a single NIXL base port for this endpoint.
                # vLLM internally computes: actual_port = base + data_parallel_rank
                # so all DP ranks in the endpoint share the same base port.
                dp_size = self._get_dp_size(endpoint.mode) or len(endpoint.gpu_indices)
                nixl_base_port = port_allocator.next_nixl_port_block(dp_size)
                for _node_rank, node in enumerate(endpoint.nodes):
                    for gpu_idx in sorted(endpoint.gpu_indices):
                        is_leader = dp_rank == 0
                        http_port = port_allocator.next_http_port(node) if is_leader else 0
                        bootstrap_port = (
                            port_allocator.next_bootstrap_port(node)
                            if endpoint.mode == "prefill" and is_leader
                            else None
                        )
                        kv_events_port = port_allocator.next_kv_events_port()
                        nixl_port = nixl_base_port

                        processes.append(
                            Process(
                                node=node,
                                gpu_indices=frozenset([gpu_idx]),  # Single GPU per process
                                sys_port=current_sys_port,
                                http_port=http_port,
                                endpoint_mode=endpoint.mode,
                                endpoint_index=endpoint.index,
                                node_rank=dp_rank,  # dp_rank stored in node_rank for now
                                bootstrap_port=bootstrap_port,
                                kv_events_port=kv_events_port,
                                nixl_port=nixl_port,
                                dp_rpc_port=dp_rpc_port,
                            )
                        )
                        current_sys_port += 1
                        dp_rank += 1

        return processes

    def _dp_per_node_endpoints_to_processes(
        self,
        endpoints: list[Endpoint],
        base_sys_port: int = DYN_SYSTEM_PORT_BASE,
        port_allocator: NodePortAllocator | None = None,
    ) -> list[Process]:
        """Convert DP endpoints to one process per node."""
        from srtctl.core.topology import NodePortAllocator, Process, endpoints_to_processes

        processes: list[Process] = []
        current_sys_port = base_sys_port
        if port_allocator is None:
            port_allocator = NodePortAllocator()

        for endpoint in endpoints:
            if not self._is_dp_mode(endpoint.mode):
                non_dp = endpoints_to_processes(
                    [endpoint],
                    base_sys_port=current_sys_port,
                    port_allocator=port_allocator,
                )
                processes.extend(non_dp)
                current_sys_port += len(non_dp)
                continue

            dp_size = self._get_dp_size(endpoint.mode) or endpoint.total_gpus
            if dp_size != endpoint.total_gpus:
                raise ValueError(
                    f"{endpoint.mode} data-parallel-size={dp_size} does not match "
                    f"the endpoint's {endpoint.total_gpus} allocated GPUs"
                )

            local_dp_size = len(endpoint.gpu_indices)
            dp_rpc_port = port_allocator.next_dp_rpc_port(endpoint.leader_node)
            nixl_base_port = port_allocator.next_nixl_port_block(dp_size)
            dp_start_rank = 0

            for node in endpoint.nodes:
                processes.append(
                    Process(
                        node=node,
                        gpu_indices=endpoint.gpu_indices,
                        sys_port=current_sys_port,
                        http_port=port_allocator.next_http_port(node),
                        endpoint_mode=endpoint.mode,
                        endpoint_index=endpoint.index,
                        node_rank=dp_start_rank,
                        bootstrap_port=(
                            port_allocator.next_bootstrap_port(node) if endpoint.mode == "prefill" else None
                        ),
                        kv_events_port=port_allocator.next_kv_events_port_block(local_dp_size),
                        nixl_port=nixl_base_port,
                        dp_rpc_port=dp_rpc_port,
                        het_group=endpoint.het_group,
                    )
                )
                current_sys_port += 1
                dp_start_rank += local_dp_size

        return processes

    def build_worker_command(
        self,
        process: Process,
        endpoint_processes: list[Process],
        runtime: RuntimeContext,
        frontend_type: str = "dynamo",
        nsys_prefix: list[str] | None = None,
        dump_config_path: Path | None = None,
        profiling: ProfilingConfig | None = None,
    ) -> list[str]:
        """Build the command to start a vLLM worker process.

        Args:
            process: The process to start
            endpoint_processes: All processes for this endpoint (for multi-node)
            runtime: Runtime context with paths and settings
            frontend_type: Frontend type (currently only "dynamo" supported for vLLM)
            nsys_prefix: Optional nsys profiling command prefix
            dump_config_path: Path to dump config JSON
            profiling: Profiling config; drives --profiler-config for iteration-based nsys
        """
        from srtctl.core.slurm import get_hostname_ip

        mode = process.endpoint_mode
        config = self.get_config_for_mode(mode)

        # Determine if multi-node
        endpoint_nodes = list(dict.fromkeys(p.node for p in endpoint_processes))
        is_multi_node = len(endpoint_nodes) > 1

        # Get leader IP for distributed init
        leader_ip = get_hostname_ip(endpoint_nodes[0])

        # Determine model path: HF model ID or container mount path
        # For HF models (hf:prefix), model_path contains the HF model ID (e.g., "facebook/opt-125m")
        # For local models, model is mounted to /model in the container
        model_arg = str(runtime.model_path) if runtime.is_hf_model else "/model"

        # Get served model name from config or use model path name
        served_model_name = self.get_served_model_name(runtime.model_path.name)

        # Start with nsys prefix if provided
        cmd: list[str] = list(nsys_prefix) if nsys_prefix else []

        # Base command - use dynamo.vllm module
        cmd.extend(
            [
                "python3",
                "-m",
                "dynamo.vllm",
                "--model",
                model_arg,
                "--served-model-name",
                served_model_name,
            ]
        )

        # Disaggregation mode (dynamo 1.0.0+: --is-prefill-worker/--is-decode-worker are deprecated)
        if mode in ("prefill", "decode"):
            cmd.extend(["--disaggregation-mode", mode])

        # KV connector → --kv-transfer-config (dynamo 1.0.0+: --connector was removed)
        # Check for mode-specific override first, then fall back to default.
        # Pop from config so it doesn't get added again by _config_to_cli_args.
        mode_connector = config.pop("connector", None)
        connector = mode_connector if mode_connector is not None else self.connector

        if connector and connector not in ("null", "none", None):
            kv_transfer_cfg = _connector_to_kv_transfer_config(connector)
            cmd.extend(["--kv-transfer-config", kv_transfer_cfg])

        if not self.set_cuda_visible_devices:
            device_ids = ",".join(str(i) for i in sorted(process.gpu_indices))
            if device_ids:
                cmd.extend(["--device-ids", device_ids])

        # Check if this is DP+EP mode (data-parallel-size set)
        is_dp_mode = self._is_dp_mode(mode)
        if is_dp_mode and self.get_dp_launch_mode_for_mode(mode) == "per_node":
            rpc_port_kebab = config.pop("data-parallel-rpc-port", None)
            rpc_port_snake = config.pop("data_parallel_rpc_port", None)
            config_dp_rpc_port = rpc_port_kebab or rpc_port_snake
            dp_rpc_port = process.dp_rpc_port or config_dp_rpc_port or VLLM_DATA_PARALLEL_RPC_PORT

            # These values are derived from the allocated process topology.
            config.pop("data-parallel-size-local", None)
            config.pop("data_parallel_size_local", None)
            config.pop("data-parallel-start-rank", None)
            config.pop("data_parallel_start_rank", None)

            cmd.extend(
                [
                    "--data-parallel-size-local",
                    str(len(process.gpu_indices)),
                    "--data-parallel-start-rank",
                    str(process.node_rank),
                    "--data-parallel-address",
                    leader_ip,
                    "--data-parallel-rpc-port",
                    str(dp_rpc_port),
                ]
            )

            hybrid_lb = config.get("data-parallel-hybrid-lb", config.get("data_parallel_hybrid_lb", False))
            hybrid_lb_enabled = hybrid_lb is True or (
                isinstance(hybrid_lb, str) and hybrid_lb.strip().lower() in {"1", "true", "yes", "on"}
            )
            if process.node_rank > 0 and not hybrid_lb_enabled:
                cmd.append("--headless")
        elif is_dp_mode:
            # DP+EP mode: each GPU runs its own process
            # process.node_rank is the dp_rank (set in endpoints_to_processes)
            dp_rank = process.node_rank
            # Use the per-endpoint dp_rpc_port allocated by NodePortAllocator
            # (avoids port collisions when multiple endpoints share a node)
            dp_rpc_port = (
                process.dp_rpc_port
                or config.pop("data-parallel-rpc-port", None)
                or config.pop("data_parallel_rpc_port", VLLM_DATA_PARALLEL_RPC_PORT)
            )
            # Pop from config so it doesn't get added again by _config_to_cli_args
            config.pop("data-parallel-rpc-port", None)
            config.pop("data_parallel_rpc_port", None)

            cmd.extend(
                [
                    "--data-parallel-rank",
                    str(dp_rank),
                    "--data-parallel-address",
                    leader_ip,
                    "--data-parallel-rpc-port",
                    str(dp_rpc_port),
                ]
            )
            # Note: --data-parallel-size is added via _config_to_cli_args from vllm_config
        elif is_multi_node:
            # Standard TP+PP multi-node coordination flags
            node_rank = endpoint_nodes.index(process.node)
            cmd.extend(
                [
                    "--master-addr",
                    leader_ip,
                    "--nnodes",
                    str(len(endpoint_nodes)),
                    "--node-rank",
                    str(node_rank),
                ]
            )

            # Non-leader nodes run headless
            if node_rank > 0:
                cmd.append("--headless")

        # Add request plane
        cmd.extend(["--request-plane", runtime.request_plane])

        # Add config dump path
        if dump_config_path:
            cmd.extend(["--dump-config-to", str(dump_config_path)])

        kv_cfg = self.get_kv_events_config_for_mode(mode)
        if kv_cfg and process.kv_events_port is not None:
            kv_cfg["endpoint"] = f"tcp://*:{process.kv_events_port}"
            cmd.extend(["--kv-events-config", json.dumps(kv_cfg)])

        if profiling is not None and profiling.is_nsys and not profiling.is_nsys_time:
            phase = profiling._get_phase_config(mode)
            if phase is not None and phase.start_step is not None and phase.stop_step is not None:
                config["profiler-config"] = json.dumps(
                    {
                        "profiler": "cuda",
                        "delay_iterations": phase.vllm_nsys_delay_iterations,
                        "max_iterations": phase.vllm_nsys_max_iterations,
                    }
                )

        # Add all config flags from vllm_config
        cmd.extend(_config_to_cli_args(config))

        return cmd


_CONNECTOR_MAP: dict[str, dict[str, str]] = {
    "nixl": {"kv_connector": "NixlConnector", "kv_role": "kv_both"},
    "lmcache": {"kv_connector": "LMCacheConnectorV1", "kv_role": "kv_both"},
    "kvbm": {
        "kv_connector": "DynamoConnector",
        "kv_connector_module_path": "kvbm.vllm_integration.connector",
        "kv_role": "kv_both",
    },
}


def _connector_to_kv_transfer_config(connector: str) -> str:
    """Translate a connector shorthand to a --kv-transfer-config JSON string.

    Known shorthands (e.g. "nixl", "lmcache") are expanded to the full JSON
    config expected by vLLM.  Anything else is passed through as-is (assumed
    to already be a valid JSON string).
    """
    preset = _CONNECTOR_MAP.get(connector.lower())
    if preset is not None:
        return json.dumps(preset)
    return connector


def _config_to_cli_args(config: dict[str, Any]) -> list[str]:
    """Convert config dict to CLI arguments."""
    args: list[str] = []
    for key, value in sorted(config.items()):
        flag_name = key.replace("_", "-")
        if isinstance(value, bool):
            if value:
                args.append(f"--{flag_name}")
        elif isinstance(value, list):
            args.append(f"--{flag_name}")
            args.extend(str(v) for v in value)
        elif value is not None:
            args.extend([f"--{flag_name}", str(value)])
    return args
